# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40a7828b767d4c9d6eb29974bacac5c7ec2750dda5c77c02f636658def8a16829267ef83ee8368869173459dc052a8f7c56bb6b053ad74d39d299b85a569394e

test:
  secret_key_base: c3956e1921d0d02173fd40f7517e239462a98c4ded2bb9a1c03bd60fd121a1e0576d794f7def74ad4f2e08f57f148152896620cd913952917c486c2971628773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
